export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const EXPAND_MENU = 'EXPAND_MENU'

export const SWITCH_EFFECT = 'SWITCH_EFFECT'

export const CREATE_PRODUCT = 'CREATE_PRODUCT'

export const CREATE_VARIANT = 'CREATE_VARIANT'

export const INIT_INVENTORY = 'INIT_INVENTORY'

export const GET_PRODUCT_VARIANT = 'GET_PRODUCT_VARIANT'