export const INIT_APP = 'INIT_APP'

export const TOGGLE_LOADER = 'TOGGLE_LOADER'

export const LOGIN = 'LOGIN'

export const LOGOUT = 'LOGOUT'

export const TOGGLE_IS_ROOT = 'TOGGLE_IS_ROOT'

export const EXPAND_MENU = 'EXPAND_MENU'

export const INIT_INVENTORY = 'INIT_INVENTORY'

export const INIT_PURCHASING = 'INIT_PURCHASING'

export const INIT_SUPPLIER = 'INIT_SUPPLIER'

export const INIT_WAREHOUSE = 'INIT_WAREHOUSE'

export const INIT_SALES = 'INIT_SALES'

export const INIT_NOTIFICATIONS = 'INIT_NOTIFICATIONS'

// Products
export const CREATE_PRODUCT = 'CREATE_PRODUCT'

export const CREATE_VARIANT = 'CREATE_VARIANT'

export const UPDATE_STOCK = 'UPDATE_STOCK'

export const INCREASE_STOCK = 'INCREASE_STOCK'

export const DECREASE_STOCK = 'DECREASE_STOCK'

// Purchasing
export const ADD_PURCHASE = 'ADD_PURCHASE'

export const EDIT_PURCHASE = 'EDIT_PURCHASE'

export const RECEIVE_PURCHASE = 'RECEIVE_PURCHASE'

export const CHECK_PURCHASE = 'CHECK_PURCHASE'

export const ALLOCATE_PURCHASE = 'ALLOCATE_PURCHASE'

export const STORE_PURCHASE = 'STORE_PURCHASE'

export const ADJUST_PURCHASE = 'ADJUST_PURCHASE'

export const SAVE_PURCHASE = 'SAVE_PURCHASE'

export const HANDLE_RECOMMENDATION = 'HANDLE_RECOMMENDATION'

// Warehouse
export const ALLOCATE_ITEMS = 'ALLOCATE_ITEMS'